### ISSUE TITLE
edb-debugger-0.9.21.ebuild rquires Qt5, while Qt4 >= 4.6 would suffice

### ISSUE THREAD

**Issue by sedimentation-fault** [Petross404/testing#1]
This is actually not a bug - just an observation regarding the ebuild for the 0.9.21 version of _edb-debugger._

The ebuild requires _Qt5._ However, this is not strictly necessary. Upstream says _Qt_ >= 4.6 should suffice, so I modified the RDEPEND array to:

```
RDEPEND="
    >=dev-libs/capstone-3.0
    graphviz? ( >=media-gfx/graphviz-2.38.0 )
    >=dev-qt/qtxmlpatterns-4.6
    >=dev-qt/qtgui-4.6
    >=dev-qt/qtcore-4.6
    "
```
With this modification, _edb_ can be compiled with _Qt4_ without problems (I have done so with _Qt_ 4.8).

**Comment by Petross404** [comment]
@sedimentation-fault Did you gave the user the ability to choose in what Qt version edb is going to be compiled with, via USE flag?

**Comment by sedimentation-fault** [comment]
No.

I guess most users have either _Qt4_ or _Qt5_ installed, not both. So the above will choose the installed _Qt_, as long as it fulfills the version requirements. 

AFAIR even if you have both _Qt_'s installed, the configure script will first check for _Qt5_ and then for _Qt4_. So you should be OK without a USE flag for _Qt_ version, even in this case.

My guess is that, since _qtxmlpatterns_, _qtgui_ and _qtcore_ sufficed to compile _edb_ with _Qt4_, they will also suffice with _Qt5_. The other dependencies for _Qt5_ seem to be pulled in by those 3, so (I guess) they are superfluous. Of course, with only _Qt_ 4.8 installed, I cannot check this claim - but you can. ;-)

**Comment by Petross404** [comment]
Many users have both toolkits and if it is to support an older toolkit, then the user should be asked. Qt5 is new and stable and will be the qt version that will be most used in the next few years, but anyway that is what gentoo/pentoo developers also told me.

Also yes these deps might not be necessary but once again, developers insisted that way. 

Of course you can modifye the ebuild according your needs :)
